#!/bin/sh

NAME=ramify_mysql
PATH_TO_DATA=/usr/local/mysql/data
SIZE_IN_MB=512
MYSQL_OWNER=_mysql:wheel
MYSQL_SCRIPT=/Library/StartupItems/MySQLCOM/MySQLCOM

with_stopped_mysql_do() {
  $MYSQL_SCRIPT stop
  $1
  $MYSQL_SCRIPT start
}

start_ramify() {
  sectors=$((2*1024*SIZE_IN_MB));
  device=$(hdik -drivekey system-image=yes -nomount ram://$sectors)
  newfs_hfs $device
  mount -t hfs -o union -o nobrowse $device $PATH_TO_DATA
  chown $MYSQL_OWNER $PATH_TO_DATA
}

stop_ramify() {
  diskutil unmount $PATH_TO_DATA
}

test_root() {
  if [[ $(/usr/bin/id -u) -ne 0 ]]
  then
    echo "You are using a non-privileged account"
    exit 1
  fi
}

main() {
  case "$1" in

  start)
    echo "Starting $NAME..."
    with_stopped_mysql_do start_ramify
    ;;

  stop)
    echo "Stopping $NAME"
    with_stopped_mysql_do stop_ramify
    ;;

  *)
    echo "Usage: $NAME {start|stop}"
    exit 1
    ;;

  esac
}

test_root
main $1
